name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'   

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Get previous tag
        id: prev_tag
        run: |
          echo "PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo 'none')" >> $GITHUB_ENV

      - name: Generate release notes
        run: |
          echo "## Release Notes for $GITHUB_REF_NAME" > release-notes.md
          echo "" >> release-notes.md
          if [ "$PREV_TAG" = "none" ]; then
            git log --oneline >> release-notes.md
          else
            git log $PREV_TAG..HEAD --oneline >> release-notes.md
          fi
          cat release-notes.md

      - name: Commit and push release notes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add release-notes.md
          git commit -m "Add release notes for $GITHUB_REF_NAME" || echo "No changes to commit"
          git push
